---
- name: Update group1
  hosts: g1

  tasks:
  - name: Ensure WEB directory created
    file:
      path: /home/centos/web
      state: directory

- name: Update group2
  hosts: g2

  tasks:
  - name: Ensure APP directory created
    file:
      path: /home/centos/app
      state: directory

- name: Update all Infra
  hosts: all

  tasks:
  - name: Ensure APP directory created
    file:
      path: /home/centos/common
      state: directory

  - name: Ensure patch Download
    get_url:
      dest: /home/centos/common
      url: https://github.com/Vision2Leap/new/archive/refs/heads/qa.zip
...
