---
- name: Update group1
  hosts: g1
  become: yes
  handlers: 
  - name: Restart HTTPD
    service:
      name: httpd
      state: restarted
  tasks:
  - name: Ensure SELinux Permissive
    selinux:
      policy: targeted
      state: permissive

  - name: update Config File
    copy:
      dest: /etc/httpd/conf/httpd.conf
      src: httpd.conf
    notify:
    - Restart HTTPD

  - name: update Date File
    copy:
      dest: /var/www/html/date.php
      src: date.php    
   
  - name: Install PHP
    package:
      name: php
      state: present
    notify:
    - Restart HTTPD
...
