---
- name: Update group2
  hosts: g2
  become: yes

  tasks:
  - name: Remove index file
    file:
      path: /var/www/html/index.html
      state: absent
    run_once: true
      
  - name: Ensure App deployed
    git:
      dest: /var/www/html
      repo: https://github.com/ravi2krishna/ecomm.git
     
...
